[package]
name = "units"
version = "0.1.0"
edition = "2021"

[dependencies]
common_data_types = { path = "../common_data_types" }

[build-dependencies]
csv = "1.3.0"
serde = { version = "1.0", features = [ "derive" ] }
uneval = "0.2.4"
common_data_types = { path = "../common_data_types" }